debug: true

spring:
  profiles:
    include: db,bean
  security:
    user:
      name: admin
      password: admin
  main:
    allow-bean-definition-overriding: false
  jpa:
    show-sql: true

  redis:
    password: 233333
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.yu.pojo

